#
#   ███╗░░██╗██╗░██████╗░██╗░░██╗████████╗░░░░░██╗░█████╗░██╗███╗░░██╗███████╗██████╗░
#   ████╗░██║██║██╔════╝░██║░░██║╚══██╔══╝░░░░░██║██╔══██╗██║████╗░██║██╔════╝██╔══██╗
#   ██╔██╗██║██║██║░░██╗░███████║░░░██║░░░░░░░░██║██║░░██║██║██╔██╗██║█████╗░░██████╔╝
#   ██║╚████║██║██║░░╚██╗██╔══██║░░░██║░░░██╗░░██║██║░░██║██║██║╚████║██╔══╝░░██╔══██╗
#   ██║░╚███║██║╚██████╔╝██║░░██║░░░██║░░░╚█████╔╝╚█████╔╝██║██║░╚███║███████╗██║░░██║
#   ╚═╝░░╚══╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░░╚════╝░╚═╝╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝
#
#            V 1.0.0   |   Author: MrDrag0nXYT (https://drakoshaslv.ru)
#             Source code: https://github.com/MrDrag0nXYT/NightJoiner
#

# Enable BStats metrics? You can see it here: https://bstats.org/plugin/bukkit/NightJoiner/23311
enable-metrics: true

#
# Database for storing custom join messages
# Supports SQLITE; todo: other DBs
#
database:
  type: SQLITE

#
# Join/quit and welcome messages format
# Support:
#   - MiniMessage (<#abcdef>) and Legacy (&#abcdef) formatting codes
#   - PlaceholderAPI placeholders
#
messages:
  show-in-console: true
  join:
    - ""
    - " <#ace1af>+</#ace1af> &#fcfcfc%luckperms_prefix% %player_name% &#fcfcfc%player_text%"
    - ""
  quit:
    - ""
    - " <#d45079>-</#d45079> &#fcfcfc%luckperms_prefix% %player_name% &#fcfcfc%player_text%"
    - ""

  #
  # Default join/quit messages if player not set
  #
  default:
    join: "залетел на наш сервер"
    quit: "покинул нас"

  motd:
    enabled: true
    text:
      - ""
      - " <#fcfcfc>Добро пожаловать на наш сервер, <#745c97>%player_name%</#745c97>!"
      - "  <#c0c0c0>‣ <#fcfcfc>Ваша группа: %luckperms_prefix%"
      - ""
