name: NightJoiner
version: '1.0.2'
main: zxc.mrdrag0nxyt.nightJoiner.NightJoiner
api-version: '1.18'
authors: [ mrdrag0nxyt (drakoshaslv) ]
website: https://drakoshaslv.ru
depend: [ PlaceholderAPI ]

libraries:
  - "com.zaxxer:HikariCP:5.1.0"
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0"
  - "org.xerial:sqlite-jdbc:3.47.0.0"
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-text-serializer-legacy:4.17.0"

commands:
  nightjoiner:
    aliases:
      - nj
    usage: /<command>

  setjoin:
    usage: /<command> <text>
  setquit:
    usage: /<command> <text>
  resetjoin:
    usage: /<command> <text>
  resetquit:
    usage: /<command> <text>

permissions:
  nightjoiner.player.setjoin:
    default: false
  nightjoiner.player.setquit:
    default: false

  nightjoiner.player.broadcast.join:
    default: false
  nightjoiner.player.broadcast.quit:
    default: false

  nightjoiner.admin.reload:
    default: op
  nightjoiner.admin.ban:
    default: op
  nightjoiner.admin.unban:
    default: op

  nightjoiner.*:
    default: op
    children:
      nightjoiner.admin.*: true
      nightjoiner.player.*: true

  nightjoiner.admin.*:
    default: op
    children:
      nightjoiner.admin.reload: true
      nightjoiner.admin.ban: true
      nightjoiner.admin.unban: true
      nightjoiner.player.*: true

  nightjoiner.player.*:
    default: false
    children:
      nightjoiner.player.setjoin: true
      nightjoiner.player.setquit: true
      nightjoiner.player.broadcast.join: true
      nightjoiner.player.broadcast.quit: true
